project_id = "xyremooqxapuqcrxdnpj"

[functions.call-ticket]
verify_jwt = false

[functions.create-ticket]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.setup-admin]
verify_jwt = false
